spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    org.springframework.security: info

server:
  forward-headers-strategy: framework

management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /api/health-check
  endpoint:
    health:
      enabled: true

swagger:
  servers:
    - url: http://13.209.129.138:8080
      description: "kkini dev http 서버입니다."
    - url: http://localhost:8080
      description: "kkini local 서버입니다."

