cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      signature-version: AWS4-HMAC-SHA256
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false

swagger:
  servers:
    - url: https://dev.kkinii.com
      description: "kkini dev https 서버입니다."
    - url: http://dev.kkinii.com
      description: "kkini dev http 서버입니다."
    - url: http://localhost:8080
      description: "kkini local 서버입니다."